version: '3'
services:
  api:
    image: image-viewer-api
    ports:
      - "5000:80"
    depends_on:
      - database

  ui:
    image: image-viewer-ui
    ports:
      - "3000:3000"
    depends_on:
      - api

  database:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: ""
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"